apps/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('room/<str:room_code>', views.join_room, name='join_room'),
    path('create-room', views.create_room, name='create_room'),
    path('', views.index_chat, name='index_chat')
]

chat_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

import apps.public.views, apps.chat.views

urlpatterns = [
    path('', apps.public.views.index_page),
    path('profile', apps.public.views.profile, name='profile'),
    re_path(r'^login', apps.public.views.login_view, name='login'),
    path('register', apps.public.views.register_view, name='register'),
    path('profile/my-room', apps.public.views.my_room, name='my_room'),
    path('profile/room/<str:room_code>/setting', apps.public.views.room_settings, name='room_settings'),
    path('chat/', include('apps.chat.urls'), name='chat'),
    path('api/user/', include('apps.public.api_urls')),
    path('api/chat/', include('apps.chat.api_urls')),
    path('admin/', admin.site.urls)
] + static('static/', document_root=settings.STATIC_ROOT)

apps/chat/models.py
from django.db import models
from django.contrib.auth.models import User 
import random, string , os 
from django.conf import settings

class Bot(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=33)
    message_handler = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.description or self.file_name
    
    def save(self, *args, **kwargs):
        dirname = os.path.dirname(self.file_name)
        if dirname:
            self.file_name = self.file_name.replace(dirname,'').replace('/','')
        return super().save(*args, **kwargs)

class Room(models.Model):
    ROOM_VISIBILITY = (
        (0, 'only user that know room code can join'),
        (1, 'Anyone can join, room will shown in chat index')
    )

    room_code = models.CharField(max_length=8)
    room_name = models.CharField(max_length=255)
    is_public = models.IntegerField(choices=ROOM_VISIBILITY, default=1)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    blocked_users = models.ManyToManyField(User, related_name='blocked_users_set')
    active_bots = models.ManyToManyField(Bot) 

    def save(self, room_code=True, *args, **kwargs):
        if not room_code:
            self.room_code = self.__generate_code()
        super().save(*args, **kwargs)
    
    def __repr__(self):
        return self.room_name
    
    def __str__(self):
        return self.room_name

    def __generate_code(self):
        return ''.join(random.choice(string.ascii_lowercase) for _ in range(8))

class Visitor(models.Model):
    user_agent = models.TextField(null=True)
    ip_addr = models.GenericIPAddressField()

    def save(self, *args, **kwargs):
        if self.user_agent in settings.USER_AGENT_BLACKLIST:
            return None 
        return super().save(*args, **kwargs)

    def __repr__(self):
        return '<user_agent:{}'.format(self.user_agent)    

class Chat(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __repr__(self):
        return '<from_user:{}'.format(self.from_user.username)

apps/chat/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets
from datetime import datetime, timedelta
from rest_framework.response import Response

from .permissions import RoomPermission
from . import serializers
from .models import Room, Chat

from apps.public import serializers as public_serializer
from django.shortcuts import get_object_or_404

import html

class RoomViewSets(viewsets.ModelViewSet):
    
    serializer_class = serializers.RoomSerializer
    queryset = Room.objects.filter(is_public=1).all()
    lookup_field = "room_code"
    permission_classes = [RoomPermission]


    def perform_create(self, serializer):
        room_name = serializer.validated_data.get('room_name')
        
        serializer.save(creator=self.request.user)
        serializer.save(room_name=html.escape(room_name))

        return serializer
    
    def create(self, request, *args, **kwargs):
        instance = super().create(request, *args, **kwargs)
        return Response(
            {
                "status":"success", 
                "room_code":instance.data.get('room_code')
            }
        )

    def retrieve(self, request, *args, **kwargs):
        lookup_field = self.lookup_field or self.lookup_url_kwarg

        lookup_kwargs = {lookup_field: self.kwargs[lookup_field]}
        _ = get_object_or_404(Room, **lookup_kwargs)

        queryset = Chat.objects.filter(room__room_code=self.kwargs[lookup_field], 
                                       created__range=(datetime.now() - timedelta(days=5), datetime.now()))
        serializer = serializers.ChatSerializer(queryset, many=True)
        return Response(serializer.data)

def profile(request):
    serializer = public_serializer.UserSerializer
    return render(request, 'chat/profile.html', {'serializer':serializer})

def create_room(request):
    return render(request, 'chat/create-room.html')

class ChatViewSets(viewsets.ModelViewSet):
    serializer_class = serializers.ChatSerializer
    queryset = Chat.objects.all()
        
def join_room(request, room_code):
    is_exist = Room.objects.filter(room_code=room_code).first()
    if not is_exist:
        return redirect('chat:index_chat')
    return render(request, 'chat/chat.html', context={'room_name':room_code})

def index_chat(request):

    return render(request, 'chat/index.html')

chat/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets , decorators
from rest_framework.response import Response

from .permissions import RoomPermission
from . import serializers
from .models import Room, Chat

from public import serializers as public_serializer
from django.shortcuts import get_object_or_404


class RoomViewSets(viewsets.ModelViewSet):
    
    serializer_class = serializers.RoomSerializer
    queryset = Room.objects.filter(is_public=1).all()
    lookup_field = "room_code"
    permission_classes = [RoomPermission]


    def perform_create(self, serializer):
        
        serializer.save(creator=self.request.user)
        
        return serializer
    
    def create(self, request, *args, **kwargs):
        instance = super().create(request, *args, **kwargs)
        return Response(
            {
                "status":"success", 
                "room_code":instance.data.get('room_code')
            }
        )

    def retrieve(self, request, *args, **kwargs):
        lookup_field = self.lookup_field or self.lookup_url_kwarg

        lookup_kwargs = {lookup_field: self.kwargs[lookup_field]}

        _ = get_object_or_404(Room, **lookup_kwargs)

        queryset = Chat.objects.filter(room__room_code=self.kwargs[lookup_field])
        
        serializer = serializers.ChatSerializer(queryset, many=True)
        return Response(serializer.data)

def profile(request):
    serializer = public_serializer.UserSerializer
    return render(request, 'chat/profile.html', {'serializer':serializer})

def create_room(request):
    return render(request, 'chat/create-room.html')

class ChatViewSets(viewsets.ModelViewSet):
    serializer_class = serializers.ChatSerializer
    queryset = Chat.objects.all()
        
def join_room(request, room_code):
    is_exist = Room.objects.filter(room_code=room_code).first()
    if not is_exist:
        return redirect('chat:index_chat')
    return render(request, 'chat/chat.html', context={'room_name':room_code})

def index_chat(request):

    return render(request, 'chat/index.html')

apps/chat/templates/chat/chat.html
<html>
    <head>
        <title>Chat App with Django-channels!</title>
        {% load static %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'chat/css/styles.css' %}">
        <meta name="viewport" content="user-scalable=no, width=device-width">
    </head>
<body>
    <div class="wrapper">
        <div class="header">
            <div class="container">
                <div class="header-content">
                    <h2>Room Chat</h2>
                    <a href="{% url 'room_settings' room_code=room_name %}">
                        <i class="fa fa-cog" id="btn-menu"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="chat">
            <div class="container">
                <div class="chat-content" id="chat-content">
                    <p id="loadingp">Loading ... </p>
                    
                </div>
            </div>
        </div>
        <div class="chat-input">
            <div id="form-chat">
                <div class="input">
                    <input type="text" id="message" placeholder="Type a message..." autocomplete="off" autofocus="on" required>
                    <button onclick="send_message()" type="submit" id="send-message">
                        <i class="fa fa-paper-plane"></i>
                    </button>
                </div>
            </form>
        </div>
       
    </div>
    <script>
        const current_user = "{{request.user}}"
    </script>

    
    
    <script type="text/javascript" src="{% static 'chat/js/chat.js' %} "></script>
</body>
</html>

apps/chat/templates/chat/create-room.html
{% extends 'public/base.html' %}
{% load static %}
{% block additional_head %}
    <link rel="stylesheet" href="{% static 'chat/css/styles.css' %}">
{% endblock %}
{% block content %}
<div class="container mt-5">
{% if request.user.is_authenticated %}
    <div id="message"></div>

    <div class="form-group">
        <label for="room_code" class="mb-2">Room name :</label>
        <p>
            <input type="text" id="room_code" class="input-room" name="room_name">
        </p>
    </div>
    <div class="form-check">
        <label for="room_status">Room Status</label>
        <select name="is_public" class="form-control" id="room_status">
            <option value="1">Anyone can Join</option>
            <option value="0">Only person that know room code can join</option>
        </select>
    </div>
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-outline-dark" id="create_room" onclick="make_room()">Create!</button>
    </div>
{% load static %}

<script src="{% static 'chat/js/script.js' %}" type="text/javascript"></script>
{% else %}
<p>Please <a href="{% url 'login' %}">Login</a> first to create a room</p>
{% endif %}

{% endblock %}

apps/chat/templates/chat/index.html
{% extends 'public/base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'chat/css/styles.css' %}">
{% endblock %}
{% block content %}

<div class="container mt-5">
    <div id="message"></div>
    <div class="form-group">
        <input type="hidden" id="ip_addr" value="{{ip_addr}}">
        <input type="hidden" id="user_agent" value="{{user_agent}}">
        <label for="room_code" class="mb-2">Room Code :</label>
        <p>
            <input type="text" id="room_code" class="input-room">
            <button type="submit" class="btn btn-outline-dark" id="go">Check</button>
        </p>
        <p>You can <a href="{% url 'chat:create_room' %}" class="text-danger">make your own room!</a></p>
    </div>
    <div class="d-flex justify-content-center mb-2">
        <h4>Public Rooms</h4>
    </div>

    <div class="row" id="card-row">
        
    </div>
    <div class="d-flex justify-content-center mt-2" id="button-position">
    
    </div>
    
    <div class="d-flex justify-content-center mt-5">
        <p>Past Visitors : </p>
        <p id="total_visitor">S</p>
    </div>
</div>

    <script type="text/javascript" src="{% static 'chat/js/script.js' %}"></script>
{% endblock %} 